title: Taqamtiku
author: Forestry.io
email: support@forestry.io
description: >-
  Le Restaurant Bar Grill Taqamtiku, situé au coeur de la Sicap Baobab au pied du légendaire Grand Baobab. La cours en plein air est une bouffée d'air frais et vous pouvez
  y déguster nos succulents repas frais.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io
permalink: /:title

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

